name: build
on: 
  workflow_dispatch: {}
jobs: 
  build: 
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    env: 
      CI: "true"
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm -g install yarn lerna
      - name: Build
        run: yarn build
